apiVersion: apps/v1
kind: Deployment

metadata:
  name: college-django

spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-django

  template:
    metadata:
      labels:
        app: college-django

    spec:
      containers:
        - name: college-django
          image: college-django:9
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
